version: 2

project_name: lazy-django

before:
  hooks:
    - go test ./...
    - go vet ./...

builds:
  - id: lazy-django
    main: ./cmd/lazy-django
    binary: lazy-django
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .FullCommit }}
      - -X main.date={{ .Date }}
      - -X main.builtBy=goreleaser

archives:
  - id: default
    ids:
      - lazy-django
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

homebrew_casks:
  - name: lazy-django
    binaries:
      - lazy-django
    homepage: "https://github.com/{{ .Env.GITHUB_REPOSITORY }}"
    description: "Keyboard-first TUI for Django workflows."
    repository:
      owner: "{{ .Env.HOMEBREW_TAP_OWNER }}"
      name: "{{ .Env.HOMEBREW_TAP_NAME }}"
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Casks
    commit_author:
      name: lazy-django-bot
      email: github-actions[bot]@users.noreply.github.com
