# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazy-django" do
  name "lazy-django"
  desc "Keyboard-first TUI for Django workflows."
  homepage "https://github.com/William-Blackie/lazydjango"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazy-django"

  on_macos do
    on_intel do
      url "https://github.com/William-Blackie/lazydjango/releases/download/v#{version}/lazy-django_#{version}_darwin_amd64.tar.gz"
      sha256 "475a3097f7d9f0fc530272a66787c42e93de6e257ac3ae92c63e7b7886e6a03e"
    end
    on_arm do
      url "https://github.com/William-Blackie/lazydjango/releases/download/v#{version}/lazy-django_#{version}_darwin_arm64.tar.gz"
      sha256 "1b2bcb579522f1ba1e2d327d791da1337edb54fa283b94ea842a417f6fcb54dc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/William-Blackie/lazydjango/releases/download/v#{version}/lazy-django_#{version}_linux_amd64.tar.gz"
      sha256 "eacab722abc9e315daa0622e32dc5a531bf4e71918d55446ff5f5e421c8aeb69"
    end
    on_arm do
      url "https://github.com/William-Blackie/lazydjango/releases/download/v#{version}/lazy-django_#{version}_linux_arm64.tar.gz"
      sha256 "c5b52dc3472364c484b1d87efd398464e6eb2689cbac973e3bdda2eae330e6a9"
    end
  end

  # No zap stanza required
end
