# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LazyDjango < Formula
  desc "Keyboard-first TUI for Django workflows."
  homepage "https://github.com/William-Blackie/lazydjango"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/William-Blackie/lazydjango/releases/download/v0.0.3/lazy-django_0.0.3_darwin_amd64.tar.gz"
      sha256 "dc17b396633626f1afb8b025b379951018f0d97430ed98ad6532087b4fc3b15e"

      define_method(:install) do
        bin.install "lazy-django"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/William-Blackie/lazydjango/releases/download/v0.0.3/lazy-django_0.0.3_darwin_arm64.tar.gz"
      sha256 "c51ad9fb5d587e07a77c0e2df2ccc72adc231dccd702297775e0af97c9dfb761"

      define_method(:install) do
        bin.install "lazy-django"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/William-Blackie/lazydjango/releases/download/v0.0.3/lazy-django_0.0.3_linux_amd64.tar.gz"
      sha256 "b0c545a055a9aa1cc29196c14cef690b3b656b9593cd1d9633874a48043cf25e"
      define_method(:install) do
        bin.install "lazy-django"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/William-Blackie/lazydjango/releases/download/v0.0.3/lazy-django_0.0.3_linux_arm64.tar.gz"
      sha256 "d548f45f6bfb1669fb721bd15c720c610c87150448c153a3f9f19151f4c3f568"
      define_method(:install) do
        bin.install "lazy-django"
      end
    end
  end

  test do
    system "#{bin}/lazy-django", "--version"
  end
end
