# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LazyDjango < Formula
  desc "Keyboard-first TUI for Django workflows."
  homepage "https://github.com/William-Blackie/lazydjango"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/William-Blackie/lazydjango/releases/download/v0.0.5/lazy-django_0.0.5_darwin_amd64.tar.gz"
      sha256 "ad40008f23abdb9e157f3bdfe041e437f35baeefa26bfbdb09ac48ac58f3657f"

      define_method(:install) do
        bin.install "lazy-django"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/William-Blackie/lazydjango/releases/download/v0.0.5/lazy-django_0.0.5_darwin_arm64.tar.gz"
      sha256 "829c2dc8d55fc18fee27f0b3e0a9b22af7b40feef2c5de9f159d8c7405555af9"

      define_method(:install) do
        bin.install "lazy-django"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/William-Blackie/lazydjango/releases/download/v0.0.5/lazy-django_0.0.5_linux_amd64.tar.gz"
      sha256 "6c89ab63dc35354c4ca33acab0707378fead2706f4f0caf7d43811a33c38bc39"
      define_method(:install) do
        bin.install "lazy-django"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/William-Blackie/lazydjango/releases/download/v0.0.5/lazy-django_0.0.5_linux_arm64.tar.gz"
      sha256 "bfea966db940007dac1a025ee8142cb1c0e26d2a5fa4876538b26c1c8e7d6ab5"
      define_method(:install) do
        bin.install "lazy-django"
      end
    end
  end

  test do
    system "#{bin}/lazy-django", "--version"
  end
end
